# Generated by Django 3.2.8 on 2021-10-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=64, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=64)),
                ('available', models.BooleanField(default=True)),
                ('available_from', models.DateField(null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
